-- ============================================================
-- IOS Field App — Store Seed Data (459 stores)
-- Run AFTER 001_schema.sql
-- Harvey Norman (180), JB Hi-Fi (174), The Good Guys (72),
-- Bing Lee (21), Joyce Mayne (12)
-- ============================================================

INSERT INTO ios_stores (retailer_id, name, suburb, state, postcode, visit_frequency_days)
SELECT r.id, v.name, v.suburb, v.state, v.postcode, 14
FROM (VALUES
-- HARVEY NORMAN NSW (62 stores)
  ('Harvey Norman','Alexandria','Alexandria','NSW','2015'),
  ('Harvey Norman','Armidale','Armidale','NSW','2350'),
  ('Harvey Norman','Auburn','Auburn','NSW','2144'),
  ('Harvey Norman','Balgowlah','Balgowlah','NSW','2093'),
  ('Harvey Norman','Ballina','Ballina','NSW','2478'),
  ('Harvey Norman','Batemans Bay','Batemans Bay','NSW','2536'),
  ('Harvey Norman','Belrose','Belrose','NSW','2085'),
  ('Harvey Norman','Bennetts Green','Bennetts Green','NSW','2290'),
  ('Harvey Norman','Blacktown','Blacktown','NSW','2148'),
  ('Harvey Norman','Bondi Junction','Bondi Junction','NSW','2022'),
  ('Harvey Norman','Broken Hill','Broken Hill','NSW','2880'),
  ('Harvey Norman','Campbelltown','Campbelltown','NSW','2560'),
  ('Harvey Norman','Caringbah','Caringbah','NSW','2229'),
  ('Harvey Norman','Castle Hill','Castle Hill','NSW','2154'),
  ('Harvey Norman','Charmhaven','Charmhaven','NSW','2263'),
  ('Harvey Norman','Cobar','Cobar','NSW','2835'),
  ('Harvey Norman','Coffs Harbour','Coffs Harbour','NSW','2450'),
  ('Harvey Norman','Deniliquin','Deniliquin','NSW','2710'),
  ('Harvey Norman','Dubbo','Dubbo','NSW','2830'),
  ('Harvey Norman','East Albury','East Albury','NSW','2640'),
  ('Harvey Norman','East Wagga Wagga','East Wagga Wagga','NSW','2650'),
  ('Harvey Norman','Erina','Erina','NSW','2250'),
  ('Harvey Norman','Forster','Forster','NSW','2428'),
  ('Harvey Norman','Broadway','Broadway','NSW','2007'),
  ('Harvey Norman','Gordon','Gordon','NSW','2072'),
  ('Harvey Norman','Goulburn','Goulburn','NSW','2580'),
  ('Harvey Norman','Grafton','Grafton','NSW','2460'),
  ('Harvey Norman','Griffith','Griffith','NSW','2680'),
  ('Harvey Norman','Gunnedah','Gunnedah','NSW','2380'),
  ('Harvey Norman','Hillvue','Hillvue','NSW','2340'),
  ('Harvey Norman','Hornsby','Hornsby','NSW','2077'),
  ('Harvey Norman','Inverell','Inverell','NSW','2360'),
  ('Harvey Norman','Jamisontown','Jamisontown','NSW','2750'),
  ('Harvey Norman','Kelso','Kelso','NSW','2795'),
  ('Harvey Norman','Kensington','Kensington','NSW','2033'),
  ('Harvey Norman','Kotara','Kotara','NSW','2289'),
  ('Harvey Norman','Lismore','Lismore','NSW','2480'),
  ('Harvey Norman','Lithgow','Lithgow','NSW','2790'),
  ('Harvey Norman','Liverpool','Liverpool','NSW','2170'),
  ('Harvey Norman','Maclean','Maclean','NSW','2463'),
  ('Harvey Norman','McGraths Hill','McGraths Hill','NSW','2756'),
  ('Harvey Norman','Moree','Moree','NSW','2400'),
  ('Harvey Norman','Moss Vale','Moss Vale','NSW','2577'),
  ('Harvey Norman','Mudgee','Mudgee','NSW','2850'),
  ('Harvey Norman','Murwillumbah','Murwillumbah','NSW','2484'),
  ('Harvey Norman','Muswellbrook','Muswellbrook','NSW','2333'),
  ('Harvey Norman','North Ryde','North Ryde','NSW','2113'),
  ('Harvey Norman','Orange','Orange','NSW','2800'),
  ('Harvey Norman','Parkes','Parkes','NSW','2870'),
  ('Harvey Norman','Port Macquarie','Port Macquarie','NSW','2444'),
  ('Harvey Norman','Roselands','Roselands','NSW','2196'),
  ('Harvey Norman','Rutherford','Rutherford','NSW','2320'),
  ('Harvey Norman','South Nowra','South Nowra','NSW','2541'),
  ('Harvey Norman','Taree','Taree','NSW','2430'),
  ('Harvey Norman','Taylors Beach','Taylors Beach','NSW','2316'),
  ('Harvey Norman','Temora','Temora','NSW','2666'),
  ('Harvey Norman','Tumut','Tumut','NSW','2720'),
  ('Harvey Norman','Tura Beach','Tura Beach','NSW','2548'),
  ('Harvey Norman','Tweed Heads South','Tweed Heads South','NSW','2486'),
  ('Harvey Norman','Warrawong','Warrawong','NSW','2502'),
  ('Harvey Norman','West Gosford','West Gosford','NSW','2250'),
  ('Harvey Norman','Young','Young','NSW','2594'),
-- HARVEY NORMAN VIC (40 stores)
  ('Harvey Norman','Ararat','Ararat','VIC','3377'),
  ('Harvey Norman','Bairnsdale','Bairnsdale','VIC','3875'),
  ('Harvey Norman','Broadmeadows','Broadmeadows','VIC','3047'),
  ('Harvey Norman','Chadstone','Chadstone','VIC','3148'),
  ('Harvey Norman','Chirnside Park','Chirnside Park','VIC','3116'),
  ('Harvey Norman','Corio','Corio','VIC','3214'),
  ('Harvey Norman','Dandenong South','Dandenong South','VIC','3175'),
  ('Harvey Norman','Echuca','Echuca','VIC','3564'),
  ('Harvey Norman','Frankston','Frankston','VIC','3199'),
  ('Harvey Norman','Hamilton','Hamilton','VIC','3300'),
  ('Harvey Norman','Hoppers Crossing','Hoppers Crossing','VIC','3029'),
  ('Harvey Norman','Horsham','Horsham','VIC','3400'),
  ('Harvey Norman','Kangaroo Flat','Kangaroo Flat','VIC','3555'),
  ('Harvey Norman','Kialla','Kialla','VIC','3631'),
  ('Harvey Norman','Maribyrnong','Maribyrnong','VIC','3032'),
  ('Harvey Norman','Melbourne','Melbourne','VIC','3000'),
  ('Harvey Norman','Melton','Melton','VIC','3337'),
  ('Harvey Norman','Mildura','Mildura','VIC','3500'),
  ('Harvey Norman','Moe','Moe','VIC','3825'),
  ('Harvey Norman','Moorabbin','Moorabbin','VIC','3189'),
  ('Harvey Norman','Mornington','Mornington','VIC','3931'),
  ('Harvey Norman','Morwell','Morwell','VIC','3840'),
  ('Harvey Norman','Narre Warren','Narre Warren','VIC','3805'),
  ('Harvey Norman','Nunawading','Nunawading','VIC','3131'),
  ('Harvey Norman','Preston','Preston','VIC','3072'),
  ('Harvey Norman','Richmond','Richmond','VIC','3121'),
  ('Harvey Norman','Sale','Sale','VIC','3850'),
  ('Harvey Norman','South Geelong','South Geelong','VIC','3220'),
  ('Harvey Norman','Springvale','Springvale','VIC','3171'),
  ('Harvey Norman','Sunshine North','Sunshine North','VIC','3020'),
  ('Harvey Norman','Swan Hill','Swan Hill','VIC','3585'),
  ('Harvey Norman','Taylors Lakes','Taylors Lakes','VIC','3038'),
  ('Harvey Norman','Thomastown','Thomastown','VIC','3074'),
  ('Harvey Norman','Traralgon','Traralgon','VIC','3844'),
  ('Harvey Norman','Wangaratta','Wangaratta','VIC','3677'),
  ('Harvey Norman','Warragul','Warragul','VIC','3820'),
  ('Harvey Norman','Warrnambool','Warrnambool','VIC','3280'),
  ('Harvey Norman','Waurn Ponds','Waurn Ponds','VIC','3216'),
  ('Harvey Norman','Wendouree','Wendouree','VIC','3355'),
  ('Harvey Norman','Wonthaggi','Wonthaggi','VIC','3995'),
-- HARVEY NORMAN QLD (37 stores)
  ('Harvey Norman','Aspley','Aspley','QLD','4034'),
  ('Harvey Norman','Atherton','Atherton','QLD','4883'),
  ('Harvey Norman','Ayr','Ayr','QLD','4807'),
  ('Harvey Norman','Booval','Booval','QLD','4304'),
  ('Harvey Norman','Browns Plains','Browns Plains','QLD','4118'),
  ('Harvey Norman','Bundaberg Central','Bundaberg Central','QLD','4670'),
  ('Harvey Norman','Bundall','Bundall','QLD','4217'),
  ('Harvey Norman','Burleigh Waters','Burleigh Waters','QLD','4220'),
  ('Harvey Norman','Cannonvale','Cannonvale','QLD','4802'),
  ('Harvey Norman','Capalaba','Capalaba','QLD','4157'),
  ('Harvey Norman','Carindale','Carindale','QLD','4152'),
  ('Harvey Norman','Dalby','Dalby','QLD','4405'),
  ('Harvey Norman','Eli Waters','Eli Waters','QLD','4655'),
  ('Harvey Norman','Emerald','Emerald','QLD','4720'),
  ('Harvey Norman','Everton Park','Everton Park','QLD','4053'),
  ('Harvey Norman','Fortitude Valley','Fortitude Valley','QLD','4006'),
  ('Harvey Norman','Garbutt','Garbutt','QLD','4814'),
  ('Harvey Norman','Ingham','Ingham','QLD','4850'),
  ('Harvey Norman','Innisfail','Innisfail','QLD','4860'),
  ('Harvey Norman','Kingaroy','Kingaroy','QLD','4610'),
  ('Harvey Norman','Loganholme','Loganholme','QLD','4129'),
  ('Harvey Norman','Macgregor','Macgregor','QLD','4109'),
  ('Harvey Norman','Maroochydore','Maroochydore','QLD','4558'),
  ('Harvey Norman','Maryborough','Maryborough','QLD','4650'),
  ('Harvey Norman','Monkland','Monkland','QLD','4570'),
  ('Harvey Norman','Morayfield','Morayfield','QLD','4506'),
  ('Harvey Norman','Mount Pleasant','Mount Pleasant','QLD','4740'),
  ('Harvey Norman','New Auckland','New Auckland','QLD','4680'),
  ('Harvey Norman','Noosaville','Noosaville','QLD','4566'),
  ('Harvey Norman','Norman Gardens','Norman Gardens','QLD','4701'),
  ('Harvey Norman','Oxley','Oxley','QLD','4075'),
  ('Harvey Norman','Portsmith','Portsmith','QLD','4870'),
  ('Harvey Norman','Queenton','Queenton','QLD','4820'),
  ('Harvey Norman','Rothwell','Rothwell','QLD','4022'),
  ('Harvey Norman','South Toowoomba','South Toowoomba','QLD','4350'),
  ('Harvey Norman','Townview','Townview','QLD','4825'),
  ('Harvey Norman','Warwick','Warwick','QLD','4370'),
-- HARVEY NORMAN WA (19 stores)
  ('Harvey Norman','Armadale','Armadale','WA','6112'),
  ('Harvey Norman','Broome','Broome','WA','6725'),
  ('Harvey Norman','Cannington','Cannington','WA','6107'),
  ('Harvey Norman','East Bunbury','East Bunbury','WA','6230'),
  ('Harvey Norman','Geraldton','Geraldton','WA','6530'),
  ('Harvey Norman','Joondalup','Joondalup','WA','6027'),
  ('Harvey Norman','Lange','Lange','WA','6330'),
  ('Harvey Norman','Malaga','Malaga','WA','6090'),
  ('Harvey Norman','Mandurah','Mandurah','WA','6210'),
  ('Harvey Norman','Manjimup','Manjimup','WA','6258'),
  ('Harvey Norman','Midland','Midland','WA','6056'),
  ('Harvey Norman','O''Connor','O''Connor','WA','6163'),
  ('Harvey Norman','Osborne Park','Osborne Park','WA','6017'),
  ('Harvey Norman','Pegs Creek','Pegs Creek','WA','6714'),
  ('Harvey Norman','Port Hedland','Port Hedland','WA','6721'),
  ('Harvey Norman','Port Kennedy','Port Kennedy','WA','6172'),
  ('Harvey Norman','South Kalgoorlie','South Kalgoorlie','WA','6430'),
  ('Harvey Norman','West Busselton','West Busselton','WA','6280'),
  ('Harvey Norman','West Perth','West Perth','WA','6005'),
-- HARVEY NORMAN SA (12 stores)
  ('Harvey Norman','Adelaide','Adelaide','SA','5000'),
  ('Harvey Norman','Gepps Cross','Gepps Cross','SA','5094'),
  ('Harvey Norman','Marion','Marion','SA','5043'),
  ('Harvey Norman','Mount Barker','Mount Barker','SA','5251'),
  ('Harvey Norman','Mount Gambier','Mount Gambier','SA','5290'),
  ('Harvey Norman','Noarlunga Centre','Noarlunga Centre','SA','5168'),
  ('Harvey Norman','Port Lincoln','Port Lincoln','SA','5606'),
  ('Harvey Norman','Port Pirie','Port Pirie','SA','5540'),
  ('Harvey Norman','Renmark','Renmark','SA','5341'),
  ('Harvey Norman','Smithfield','Smithfield','SA','5114'),
  ('Harvey Norman','Whyalla','Whyalla','SA','5600'),
  ('Harvey Norman','Woodville','Woodville','SA','5011'),
-- HARVEY NORMAN ACT (2 stores)
  ('Harvey Norman','Belconnen','Belconnen','ACT','2617'),
  ('Harvey Norman','Fyshwick','Fyshwick','ACT','2609'),
-- HARVEY NORMAN TAS (6 stores)
  ('Harvey Norman','Cambridge','Cambridge','TAS','7170'),
  ('Harvey Norman','Hobart','Hobart','TAS','7000'),
  ('Harvey Norman','Launceston','Launceston','TAS','7250'),
  ('Harvey Norman','Moonah','Moonah','TAS','7009'),
  ('Harvey Norman','South Burnie','South Burnie','TAS','7320'),
  ('Harvey Norman','Stony Rise','Stony Rise','TAS','7310'),
-- HARVEY NORMAN NT (2 stores)
  ('Harvey Norman','Alice Springs','Alice Springs','NT','0870'),
  ('Harvey Norman','Coonawarra','Coonawarra','NT','0820'),
-- JB HI-FI NSW (54 stores)
  ('JB Hi-Fi','Bankstown','Bankstown','NSW','2200'),
  ('JB Hi-Fi','Bathurst','Bathurst','NSW','2795'),
  ('JB Hi-Fi','Belrose','Belrose','NSW','2085'),
  ('JB Hi-Fi','Broadway','Broadway','NSW','2007'),
  ('JB Hi-Fi','Caringbah','Caringbah','NSW','2229'),
  ('JB Hi-Fi','Castle Hill (Castle Towers)','Castle Hill','NSW','2154'),
  ('JB Hi-Fi','Castle Hill (Home Hub)','Castle Hill','NSW','2154'),
  ('JB Hi-Fi','Tamworth','Tamworth','NSW','2340'),
  ('JB Hi-Fi','Charlestown','Charlestown','NSW','2290'),
  ('JB Hi-Fi','Chatswood (Chase)','Chatswood','NSW','2067'),
  ('JB Hi-Fi','Chatswood (Westfield)','Chatswood','NSW','2067'),
  ('JB Hi-Fi','Homebush','Homebush','NSW','2140'),
  ('JB Hi-Fi','Erina','Erina','NSW','2250'),
  ('JB Hi-Fi','Kotara','Kotara','NSW','2289'),
  ('JB Hi-Fi','Lake Haven','Lake Haven','NSW','2263'),
  ('JB Hi-Fi','Campbelltown','Campbelltown','NSW','2560'),
  ('JB Hi-Fi','North Ryde','North Ryde','NSW','2113'),
  ('JB Hi-Fi','Narellan','Narellan','NSW','2567'),
  ('JB Hi-Fi','Dubbo','Dubbo','NSW','2830'),
  ('JB Hi-Fi','Coffs Harbour','Coffs Harbour','NSW','2450'),
  ('JB Hi-Fi','Penrith (Homemaker)','Penrith','NSW','2750'),
  ('JB Hi-Fi','Penrith (Westfield)','Penrith','NSW','2750'),
  ('JB Hi-Fi','Roselands','Roselands','NSW','2196'),
  ('JB Hi-Fi','Rouse Hill','Rouse Hill','NSW','2155'),
  ('JB Hi-Fi','Glendale','Glendale','NSW','2285'),
  ('JB Hi-Fi','East Maitland','East Maitland','NSW','2323'),
  ('JB Hi-Fi','Merrylands','Merrylands','NSW','2160'),
  ('JB Hi-Fi','Shellharbour','Shellharbour','NSW','2529'),
  ('JB Hi-Fi','Wetherill Park','Wetherill Park','NSW','2164'),
  ('JB Hi-Fi','Kensington','Kensington','NSW','2033'),
  ('JB Hi-Fi','Sydney (Galeries)','Sydney','NSW','2000'),
  ('JB Hi-Fi','Ryde','Ryde','NSW','2112'),
  ('JB Hi-Fi','Tweed Heads South','Tweed Heads South','NSW','2486'),
  ('JB Hi-Fi','Warriewood','Warriewood','NSW','2102'),
  ('JB Hi-Fi','Bondi Junction','Bondi Junction','NSW','2022'),
  ('JB Hi-Fi','Eastgardens','Eastgardens','NSW','2036'),
  ('JB Hi-Fi','Hornsby','Hornsby','NSW','2077'),
  ('JB Hi-Fi','Hurstville','Hurstville','NSW','2220'),
  ('JB Hi-Fi','Liverpool','Liverpool','NSW','2170'),
  ('JB Hi-Fi','Miranda','Miranda','NSW','2228'),
  ('JB Hi-Fi','Mount Druitt','Mount Druitt','NSW','2770'),
  ('JB Hi-Fi','Parramatta','Parramatta','NSW','2150'),
  ('JB Hi-Fi','Tuggerah','Tuggerah','NSW','2259'),
  ('JB Hi-Fi','Brookvale','Brookvale','NSW','2100'),
  ('JB Hi-Fi','Blacktown','Blacktown','NSW','2148'),
  ('JB Hi-Fi','Sydney (Westfield)','Sydney','NSW','2000'),
  ('JB Hi-Fi','Sydney (World Square)','Sydney','NSW','2000'),
  ('JB Hi-Fi','Wollongong Central','Wollongong','NSW','2500'),
  ('JB Hi-Fi','Warrawong','Warrawong','NSW','2502'),
  ('JB Hi-Fi','Albury','Albury','NSW','2640'),
  ('JB Hi-Fi','Artarmon','Artarmon','NSW','2064'),
  ('JB Hi-Fi','Port Macquarie','Port Macquarie','NSW','2444'),
  ('JB Hi-Fi','Wagga Wagga','Wagga Wagga','NSW','2650'),
  ('JB Hi-Fi','Leichhardt','Leichhardt','NSW','2040'),
-- JB HI-FI VIC (49 stores)
  ('JB Hi-Fi','Melbourne (Bourke St)','Melbourne','VIC','3004'),
  ('JB Hi-Fi','Brunswick','Brunswick','VIC','3056'),
  ('JB Hi-Fi','Frankston','Frankston','VIC','3199'),
  ('JB Hi-Fi','Broadmeadows','Broadmeadows','VIC','3047'),
  ('JB Hi-Fi','Sunshine','Sunshine','VIC','3020'),
  ('JB Hi-Fi','Chadstone','Chadstone','VIC','3148'),
  ('JB Hi-Fi','Chirnside Park','Chirnside Park','VIC','3116'),
  ('JB Hi-Fi','Craigieburn','Craigieburn','VIC','3064'),
  ('JB Hi-Fi','Cranbourne (Homemaker)','Cranbourne','VIC','3977'),
  ('JB Hi-Fi','Cranbourne (High St)','Cranbourne','VIC','3977'),
  ('JB Hi-Fi','Essendon Fields','Essendon Fields','VIC','3041'),
  ('JB Hi-Fi','South Wharf','South Wharf','VIC','3006'),
  ('JB Hi-Fi','Ringwood','Ringwood','VIC','3134'),
  ('JB Hi-Fi','Forest Hill','Forest Hill','VIC','3131'),
  ('JB Hi-Fi','Greensborough','Greensborough','VIC','3088'),
  ('JB Hi-Fi','Maribyrnong','Maribyrnong','VIC','3032'),
  ('JB Hi-Fi','Dandenong','Dandenong','VIC','3175'),
  ('JB Hi-Fi','Geelong','Geelong','VIC','3220'),
  ('JB Hi-Fi','Melbourne (La Trobe St)','Melbourne','VIC','3000'),
  ('JB Hi-Fi','Mildura','Mildura','VIC','3500'),
  ('JB Hi-Fi','Preston','Preston','VIC','3072'),
  ('JB Hi-Fi','Epping','Epping','VIC','3076'),
  ('JB Hi-Fi','Werribee','Werribee','VIC','3030'),
  ('JB Hi-Fi','Keysborough','Keysborough','VIC','3173'),
  ('JB Hi-Fi','Springvale','Springvale','VIC','3171'),
  ('JB Hi-Fi','Glen Waverley','Glen Waverley','VIC','3150'),
  ('JB Hi-Fi','Richmond','Richmond','VIC','3121'),
  ('JB Hi-Fi','Taylors Lakes','Taylors Lakes','VIC','3038'),
  ('JB Hi-Fi','Airport West','Airport West','VIC','3042'),
  ('JB Hi-Fi','Doncaster','Doncaster','VIC','3108'),
  ('JB Hi-Fi','Narre Warren','Narre Warren','VIC','3805'),
  ('JB Hi-Fi','Wantirna South','Wantirna South','VIC','3152'),
  ('JB Hi-Fi','Mill Park','Mill Park','VIC','3082'),
  ('JB Hi-Fi','Cheltenham','Cheltenham','VIC','3192'),
  ('JB Hi-Fi','Melton West','Melton West','VIC','3337'),
  ('JB Hi-Fi','Altona North','Altona North','VIC','3025'),
  ('JB Hi-Fi','Ballarat','Ballarat','VIC','3350'),
  ('JB Hi-Fi','Bendigo','Bendigo','VIC','3550'),
  ('JB Hi-Fi','Brighton East','Brighton East','VIC','3187'),
  ('JB Hi-Fi','Camberwell','Camberwell','VIC','3124'),
  ('JB Hi-Fi','Hoppers Crossing','Hoppers Crossing','VIC','3029'),
  ('JB Hi-Fi','Mornington','Mornington','VIC','3931'),
  ('JB Hi-Fi','Nunawading','Nunawading','VIC','3131'),
  ('JB Hi-Fi','Pakenham','Pakenham','VIC','3810'),
  ('JB Hi-Fi','Prahran','Prahran','VIC','3181'),
  ('JB Hi-Fi','Thomastown','Thomastown','VIC','3074'),
  ('JB Hi-Fi','Traralgon','Traralgon','VIC','3844'),
  ('JB Hi-Fi','Warrnambool','Warrnambool','VIC','3280'),
  ('JB Hi-Fi','Waurn Ponds','Waurn Ponds','VIC','3216'),
-- JB HI-FI QLD (35 stores)
  ('JB Hi-Fi','Southport','Southport','QLD','4215'),
  ('JB Hi-Fi','Cairns (Central)','Cairns','QLD','4870'),
  ('JB Hi-Fi','Mackay','Mackay','QLD','4740'),
  ('JB Hi-Fi','Bald Hills','Bald Hills','QLD','4036'),
  ('JB Hi-Fi','Garbutt','Garbutt','QLD','4814'),
  ('JB Hi-Fi','Earlville','Earlville','QLD','4870'),
  ('JB Hi-Fi','Biggera Waters','Biggera Waters','QLD','4216'),
  ('JB Hi-Fi','Helensvale','Helensvale','QLD','4212'),
  ('JB Hi-Fi','Loganholme','Loganholme','QLD','4129'),
  ('JB Hi-Fi','Indooroopilly','Indooroopilly','QLD','4068'),
  ('JB Hi-Fi','Ipswich','Ipswich','QLD','4305'),
  ('JB Hi-Fi','Buddina','Buddina','QLD','4575'),
  ('JB Hi-Fi','Brisbane City (MacArthur)','Brisbane City','QLD','4000'),
  ('JB Hi-Fi','Morayfield','Morayfield','QLD','4506'),
  ('JB Hi-Fi','Mount Ommaney','Mount Ommaney','QLD','4074'),
  ('JB Hi-Fi','Springfield','Springfield','QLD','4300'),
  ('JB Hi-Fi','Broadbeach','Broadbeach','QLD','4218'),
  ('JB Hi-Fi','Brisbane City (Queen St)','Brisbane City','QLD','4000'),
  ('JB Hi-Fi','Robina','Robina','QLD','4230'),
  ('JB Hi-Fi','Burleigh Waters','Burleigh Waters','QLD','4220'),
  ('JB Hi-Fi','Hervey Bay','Hervey Bay','QLD','4655'),
  ('JB Hi-Fi','Rockhampton','Rockhampton','QLD','4701'),
  ('JB Hi-Fi','Bundaberg','Bundaberg','QLD','4670'),
  ('JB Hi-Fi','Maroochydore (Home)','Maroochydore','QLD','4558'),
  ('JB Hi-Fi','Maroochydore (Sunshine Plaza)','Maroochydore','QLD','4558'),
  ('JB Hi-Fi','Browns Plains','Browns Plains','QLD','4118'),
  ('JB Hi-Fi','Carindale','Carindale','QLD','4152'),
  ('JB Hi-Fi','Chermside','Chermside','QLD','4032'),
  ('JB Hi-Fi','Coomera','Coomera','QLD','4209'),
  ('JB Hi-Fi','Upper Mount Gravatt','Upper Mount Gravatt','QLD','4122'),
  ('JB Hi-Fi','North Lakes','North Lakes','QLD','4509'),
  ('JB Hi-Fi','Thuringowa Central','Thuringowa Central','QLD','4817'),
  ('JB Hi-Fi','Capalaba','Capalaba','QLD','4157'),
  ('JB Hi-Fi','Toowoomba','Toowoomba','QLD','4350'),
  ('JB Hi-Fi','Oxley','Oxley','QLD','4075'),
-- JB HI-FI WA (16 stores)
  ('JB Hi-Fi','Armadale','Armadale','WA','6112'),
  ('JB Hi-Fi','Belmont','Belmont','WA','6105'),
  ('JB Hi-Fi','Claremont','Claremont','WA','6010'),
  ('JB Hi-Fi','Success','Success','WA','6164'),
  ('JB Hi-Fi','Perth (Hay St)','Perth','WA','6000'),
  ('JB Hi-Fi','Perth (Murray St)','Perth','WA','6000'),
  ('JB Hi-Fi','Karrinyup','Karrinyup','WA','6018'),
  ('JB Hi-Fi','Joondalup','Joondalup','WA','6027'),
  ('JB Hi-Fi','Mandurah','Mandurah','WA','6210'),
  ('JB Hi-Fi','Midland','Midland','WA','6056'),
  ('JB Hi-Fi','Clarkson','Clarkson','WA','6030'),
  ('JB Hi-Fi','Cannington (Primewest)','Cannington','WA','6107'),
  ('JB Hi-Fi','Rockingham','Rockingham','WA','6168'),
  ('JB Hi-Fi','Booragoon','Booragoon','WA','6154'),
  ('JB Hi-Fi','Cannington (Carousel)','Cannington','WA','6107'),
  ('JB Hi-Fi','Hillarys','Hillarys','WA','6025'),
-- JB HI-FI SA (9 stores)
  ('JB Hi-Fi','Noarlunga Centre','Noarlunga Centre','SA','5168'),
  ('JB Hi-Fi','Elizabeth','Elizabeth','SA','5112'),
  ('JB Hi-Fi','Gepps Cross','Gepps Cross','SA','5094'),
  ('JB Hi-Fi','Mile End','Mile End','SA','5031'),
  ('JB Hi-Fi','Melrose Park','Melrose Park','SA','5039'),
  ('JB Hi-Fi','Smithfield','Smithfield','SA','5114'),
  ('JB Hi-Fi','Adelaide','Adelaide','SA','5000'),
  ('JB Hi-Fi','Marion','Marion','SA','5043'),
  ('JB Hi-Fi','West Lakes','West Lakes','SA','5021'),
-- JB HI-FI ACT (5 stores)
  ('JB Hi-Fi','Canberra','Canberra','ACT','2601'),
  ('JB Hi-Fi','Fyshwick','Fyshwick','ACT','2609'),
  ('JB Hi-Fi','Tuggeranong','Tuggeranong','ACT','2900'),
  ('JB Hi-Fi','Belconnen','Belconnen','ACT','2617'),
  ('JB Hi-Fi','Woden','Woden','ACT','2606'),
-- JB HI-FI TAS (2 stores)
  ('JB Hi-Fi','Rosny Park','Rosny Park','TAS','7018'),
  ('JB Hi-Fi','Hobart','Hobart','TAS','7000'),
-- JB HI-FI NT (2 stores)
  ('JB Hi-Fi','Casuarina','Casuarina','NT','0810'),
  ('JB Hi-Fi','Berrimah','Berrimah','NT','0828'),
-- THE GOOD GUYS NSW (20 stores)
  ('The Good Guys','Alexandria','Alexandria','NSW','2015'),
  ('The Good Guys','Artarmon','Artarmon','NSW','2064'),
  ('The Good Guys','Auburn','Auburn','NSW','2144'),
  ('The Good Guys','Bankstown','Bankstown','NSW','2200'),
  ('The Good Guys','Bathurst','Bathurst','NSW','2795'),
  ('The Good Guys','Campbelltown','Campbelltown','NSW','2560'),
  ('The Good Guys','Casula','Casula','NSW','2170'),
  ('The Good Guys','Castle Hill','Castle Hill','NSW','2154'),
  ('The Good Guys','Dubbo','Dubbo','NSW','2830'),
  ('The Good Guys','Erina','Erina','NSW','2250'),
  ('The Good Guys','Kotara','Kotara','NSW','2289'),
  ('The Good Guys','Kensington','Kensington','NSW','2033'),
  ('The Good Guys','Port Macquarie','Port Macquarie','NSW','2444'),
  ('The Good Guys','Prospect','Prospect','NSW','2148'),
  ('The Good Guys','Rockdale','Rockdale','NSW','2216'),
  ('The Good Guys','Tamworth','Tamworth','NSW','2340'),
  ('The Good Guys','Tempe','Tempe','NSW','2044'),
  ('The Good Guys','Tweed Heads South','Tweed Heads South','NSW','2486'),
  ('The Good Guys','Warners Bay','Warners Bay','NSW','2282'),
  ('The Good Guys','Wetherill Park','Wetherill Park','NSW','2164'),
-- THE GOOD GUYS VIC (20 stores)
  ('The Good Guys','Ballarat','Ballarat','VIC','3350'),
  ('The Good Guys','Bayswater','Bayswater','VIC','3153'),
  ('The Good Guys','Bendigo','Bendigo','VIC','3550'),
  ('The Good Guys','Chadstone','Chadstone','VIC','3148'),
  ('The Good Guys','Chirnside Park','Chirnside Park','VIC','3116'),
  ('The Good Guys','Cranbourne','Cranbourne','VIC','3977'),
  ('The Good Guys','Dandenong','Dandenong','VIC','3175'),
  ('The Good Guys','Essendon Fields','Essendon Fields','VIC','3041'),
  ('The Good Guys','Frankston','Frankston','VIC','3199'),
  ('The Good Guys','Geelong','Geelong','VIC','3220'),
  ('The Good Guys','Hoppers Crossing','Hoppers Crossing','VIC','3029'),
  ('The Good Guys','Maribyrnong','Maribyrnong','VIC','3032'),
  ('The Good Guys','Melton','Melton','VIC','3337'),
  ('The Good Guys','Mentone','Mentone','VIC','3194'),
  ('The Good Guys','Nunawading','Nunawading','VIC','3131'),
  ('The Good Guys','Preston','Preston','VIC','3072'),
  ('The Good Guys','Springvale','Springvale','VIC','3171'),
  ('The Good Guys','Taylors Lakes','Taylors Lakes','VIC','3038'),
  ('The Good Guys','Thomastown','Thomastown','VIC','3074'),
  ('The Good Guys','Traralgon','Traralgon','VIC','3844'),
-- THE GOOD GUYS QLD (16 stores)
  ('The Good Guys','Bald Hills','Bald Hills','QLD','4036'),
  ('The Good Guys','Browns Plains','Browns Plains','QLD','4118'),
  ('The Good Guys','Bundaberg','Bundaberg','QLD','4670'),
  ('The Good Guys','Capalaba','Capalaba','QLD','4157'),
  ('The Good Guys','Garbutt','Garbutt','QLD','4814'),
  ('The Good Guys','Helensvale','Helensvale','QLD','4212'),
  ('The Good Guys','Ipswich','Ipswich','QLD','4305'),
  ('The Good Guys','Loganholme','Loganholme','QLD','4129'),
  ('The Good Guys','Lutwyche','Lutwyche','QLD','4030'),
  ('The Good Guys','Maroochydore','Maroochydore','QLD','4558'),
  ('The Good Guys','North Lakes','North Lakes','QLD','4509'),
  ('The Good Guys','Oxley','Oxley','QLD','4075'),
  ('The Good Guys','Rockhampton','Rockhampton','QLD','4701'),
  ('The Good Guys','Shailer Park','Shailer Park','QLD','4128'),
  ('The Good Guys','Tingalpa','Tingalpa','QLD','4173'),
  ('The Good Guys','Toowoomba','Toowoomba','QLD','4350'),
-- THE GOOD GUYS WA (11 stores)
  ('The Good Guys','Belmont','Belmont','WA','6104'),
  ('The Good Guys','Bunbury','Bunbury','WA','6230'),
  ('The Good Guys','Butler','Butler','WA','6036'),
  ('The Good Guys','Cannington','Cannington','WA','6107'),
  ('The Good Guys','Clarkson','Clarkson','WA','6030'),
  ('The Good Guys','Geraldton','Geraldton','WA','6530'),
  ('The Good Guys','Joondalup','Joondalup','WA','6027'),
  ('The Good Guys','Malaga','Malaga','WA','6090'),
  ('The Good Guys','Midland','Midland','WA','6056'),
  ('The Good Guys','O''Connor','O''Connor','WA','6163'),
  ('The Good Guys','Osborne Park','Osborne Park','WA','6017'),
-- THE GOOD GUYS SA (3 stores)
  ('The Good Guys','Gepps Cross','Gepps Cross','SA','5094'),
  ('The Good Guys','Hectorville','Hectorville','SA','5073'),
  ('The Good Guys','Mile End','Mile End','SA','5031'),
-- THE GOOD GUYS ACT (3 stores)
  ('The Good Guys','Belconnen','Belconnen','ACT','2617'),
  ('The Good Guys','Fyshwick','Fyshwick','ACT','2609'),
  ('The Good Guys','Tuggeranong','Tuggeranong','ACT','2900'),
-- BING LEE NSW (19 stores)
  ('Bing Lee','Alexandria','Alexandria','NSW','2015'),
  ('Bing Lee','Albury','Albury','NSW','2640'),
  ('Bing Lee','Armidale','Armidale','NSW','2350'),
  ('Bing Lee','Balgowlah','Balgowlah','NSW','2093'),
  ('Bing Lee','Blacktown','Blacktown','NSW','2148'),
  ('Bing Lee','Bowral','Bowral','NSW','2576'),
  ('Bing Lee','Campbelltown','Campbelltown','NSW','2560'),
  ('Bing Lee','Carlingford','Carlingford','NSW','2118'),
  ('Bing Lee','Casula','Casula','NSW','2170'),
  ('Bing Lee','Chatswood','Chatswood','NSW','2067'),
  ('Bing Lee','Hornsby','Hornsby','NSW','2077'),
  ('Bing Lee','Kensington','Kensington','NSW','2033'),
  ('Bing Lee','Liverpool','Liverpool','NSW','2170'),
  ('Bing Lee','Mount Druitt','Mount Druitt','NSW','2770'),
  ('Bing Lee','North Ryde','North Ryde','NSW','2113'),
  ('Bing Lee','Old Guildford','Old Guildford','NSW','2161'),
  ('Bing Lee','Prospect','Prospect','NSW','2148'),
  ('Bing Lee','Rhodes','Rhodes','NSW','2138'),
  ('Bing Lee','Rockdale','Rockdale','NSW','2216'),
-- BING LEE VIC (1 store)
  ('Bing Lee','Wodonga','Wodonga','VIC','3690'),
-- BING LEE ACT (1 store)
  ('Bing Lee','Fyshwick','Fyshwick','ACT','2609'),
-- JOYCE MAYNE NSW (4 stores)
  ('Joyce Mayne','Rutherford','Rutherford','NSW','2320'),
  ('Joyce Mayne','South Nowra','South Nowra','NSW','2541'),
  ('Joyce Mayne','Wagga Wagga','Wagga Wagga','NSW','2650'),
  ('Joyce Mayne','Warrawong','Warrawong','NSW','2502'),
-- JOYCE MAYNE QLD (7 stores)
  ('Joyce Mayne','Garbutt','Garbutt','QLD','4814'),
  ('Joyce Mayne','Maroochydore','Maroochydore','QLD','4558'),
  ('Joyce Mayne','Morayfield','Morayfield','QLD','4506'),
  ('Joyce Mayne','Norman Gardens','Norman Gardens','QLD','4701'),
  ('Joyce Mayne','Sippy Downs','Sippy Downs','QLD','4556'),
  ('Joyce Mayne','South Toowoomba','South Toowoomba','QLD','4350'),
  ('Joyce Mayne','West End','West End','QLD','4101'),
-- JOYCE MAYNE NT (1 store)
  ('Joyce Mayne','Berrimah','Berrimah','NT','0828')
) AS v(retailer_name, name, suburb, state, postcode)
JOIN ios_retailers r ON r.name = v.retailer_name
ON CONFLICT DO NOTHING;
